spring:
  application:
    name: events-application
  server:
    port: 9091
  datasource:
    url: jdbc:postgresql://localhost:5432/events?createDatabaseIfNotExist=true
    username: keneth
    password: korir
  jpa:
    database: POSTGRESQL
    show-sql: true  # Use `show-sql` instead of `show`
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgresSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: kipyegonkeneth03@gmail.com
    password: ldmrhjnebqxxfxsn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
        enabled: true
